version: "3.7"

services:
  db:
    image: postgres:12-alpine
    container_name: fantasy
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: secret