output   = "sqlboiler"
wipe     = true
pkgname  = "sqlboiler"
no-context = true


[mysql]
  dbname  = "fantasy"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = ""
  sslmode = "false"