// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	ClubMatchups     string
	Clubs            string
	Leagues          string
	PlayerRounds     string
	Players          string
	Round            string
	TeamMatchups     string
	TeamPlayers      string
	TeamRoundPlayers string
	TeamRounds       string
	Teams            string
	TradePlayers     string
	Trades           string
	Users            string
	Waiver           string
	SchemaMigrations string
}{
	ClubMatchups:     "ClubMatchups",
	Clubs:            "Clubs",
	Leagues:          "Leagues",
	PlayerRounds:     "PlayerRounds",
	Players:          "Players",
	Round:            "Round",
	TeamMatchups:     "TeamMatchups",
	TeamPlayers:      "TeamPlayers",
	TeamRoundPlayers: "TeamRoundPlayers",
	TeamRounds:       "TeamRounds",
	Teams:            "Teams",
	TradePlayers:     "TradePlayers",
	Trades:           "Trades",
	Users:            "Users",
	Waiver:           "Waiver",
	SchemaMigrations: "schema_migrations",
}
