// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testClubMatchups(t *testing.T) {
	t.Parallel()

	query := ClubMatchups()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testClubMatchupsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testClubMatchupsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ClubMatchups().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testClubMatchupsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ClubMatchupSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testClubMatchupsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ClubMatchupExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ClubMatchup exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ClubMatchupExists to return true, but got false.")
	}
}

func testClubMatchupsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	clubMatchupFound, err := FindClubMatchup(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if clubMatchupFound == nil {
		t.Error("want a record, got nil")
	}
}

func testClubMatchupsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ClubMatchups().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testClubMatchupsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ClubMatchups().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testClubMatchupsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	clubMatchupOne := &ClubMatchup{}
	clubMatchupTwo := &ClubMatchup{}
	if err = randomize.Struct(seed, clubMatchupOne, clubMatchupDBTypes, false, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}
	if err = randomize.Struct(seed, clubMatchupTwo, clubMatchupDBTypes, false, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = clubMatchupOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = clubMatchupTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ClubMatchups().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testClubMatchupsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	clubMatchupOne := &ClubMatchup{}
	clubMatchupTwo := &ClubMatchup{}
	if err = randomize.Struct(seed, clubMatchupOne, clubMatchupDBTypes, false, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}
	if err = randomize.Struct(seed, clubMatchupTwo, clubMatchupDBTypes, false, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = clubMatchupOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = clubMatchupTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func clubMatchupBeforeInsertHook(e boil.Executor, o *ClubMatchup) error {
	*o = ClubMatchup{}
	return nil
}

func clubMatchupAfterInsertHook(e boil.Executor, o *ClubMatchup) error {
	*o = ClubMatchup{}
	return nil
}

func clubMatchupAfterSelectHook(e boil.Executor, o *ClubMatchup) error {
	*o = ClubMatchup{}
	return nil
}

func clubMatchupBeforeUpdateHook(e boil.Executor, o *ClubMatchup) error {
	*o = ClubMatchup{}
	return nil
}

func clubMatchupAfterUpdateHook(e boil.Executor, o *ClubMatchup) error {
	*o = ClubMatchup{}
	return nil
}

func clubMatchupBeforeDeleteHook(e boil.Executor, o *ClubMatchup) error {
	*o = ClubMatchup{}
	return nil
}

func clubMatchupAfterDeleteHook(e boil.Executor, o *ClubMatchup) error {
	*o = ClubMatchup{}
	return nil
}

func clubMatchupBeforeUpsertHook(e boil.Executor, o *ClubMatchup) error {
	*o = ClubMatchup{}
	return nil
}

func clubMatchupAfterUpsertHook(e boil.Executor, o *ClubMatchup) error {
	*o = ClubMatchup{}
	return nil
}

func testClubMatchupsHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &ClubMatchup{}
	o := &ClubMatchup{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ClubMatchup object: %s", err)
	}

	AddClubMatchupHook(boil.BeforeInsertHook, clubMatchupBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	clubMatchupBeforeInsertHooks = []ClubMatchupHook{}

	AddClubMatchupHook(boil.AfterInsertHook, clubMatchupAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	clubMatchupAfterInsertHooks = []ClubMatchupHook{}

	AddClubMatchupHook(boil.AfterSelectHook, clubMatchupAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	clubMatchupAfterSelectHooks = []ClubMatchupHook{}

	AddClubMatchupHook(boil.BeforeUpdateHook, clubMatchupBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	clubMatchupBeforeUpdateHooks = []ClubMatchupHook{}

	AddClubMatchupHook(boil.AfterUpdateHook, clubMatchupAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	clubMatchupAfterUpdateHooks = []ClubMatchupHook{}

	AddClubMatchupHook(boil.BeforeDeleteHook, clubMatchupBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	clubMatchupBeforeDeleteHooks = []ClubMatchupHook{}

	AddClubMatchupHook(boil.AfterDeleteHook, clubMatchupAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	clubMatchupAfterDeleteHooks = []ClubMatchupHook{}

	AddClubMatchupHook(boil.BeforeUpsertHook, clubMatchupBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	clubMatchupBeforeUpsertHooks = []ClubMatchupHook{}

	AddClubMatchupHook(boil.AfterUpsertHook, clubMatchupAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	clubMatchupAfterUpsertHooks = []ClubMatchupHook{}
}

func testClubMatchupsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testClubMatchupsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(clubMatchupColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testClubMatchupToOneClubUsingAwayClubClub(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local ClubMatchup
	var foreign Club

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, clubDBTypes, false, clubColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Club struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.AwayClub, foreign.ID)
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.AwayClubClub().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ClubMatchupSlice{&local}
	if err = local.L.LoadAwayClubClub(tx, false, (*[]*ClubMatchup)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.AwayClubClub == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.AwayClubClub = nil
	if err = local.L.LoadAwayClubClub(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.AwayClubClub == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testClubMatchupToOneClubUsingHomeClubClub(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local ClubMatchup
	var foreign Club

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, clubDBTypes, false, clubColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Club struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.HomeClub, foreign.ID)
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.HomeClubClub().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ClubMatchupSlice{&local}
	if err = local.L.LoadHomeClubClub(tx, false, (*[]*ClubMatchup)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.HomeClubClub == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.HomeClubClub = nil
	if err = local.L.LoadHomeClubClub(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.HomeClubClub == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testClubMatchupToOneRoundUsingRound(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local ClubMatchup
	var foreign Round

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, roundDBTypes, false, roundColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Round struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.RoundID, foreign.ID)
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Round().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ClubMatchupSlice{&local}
	if err = local.L.LoadRound(tx, false, (*[]*ClubMatchup)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Round == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Round = nil
	if err = local.L.LoadRound(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Round == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testClubMatchupToOneSetOpClubUsingAwayClubClub(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a ClubMatchup
	var b, c Club

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, clubMatchupDBTypes, false, strmangle.SetComplement(clubMatchupPrimaryKeyColumns, clubMatchupColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, clubDBTypes, false, strmangle.SetComplement(clubPrimaryKeyColumns, clubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, clubDBTypes, false, strmangle.SetComplement(clubPrimaryKeyColumns, clubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Club{&b, &c} {
		err = a.SetAwayClubClub(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.AwayClubClub != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AwayClubClubMatchups[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.AwayClub, x.ID) {
			t.Error("foreign key was wrong value", a.AwayClub)
		}

		zero := reflect.Zero(reflect.TypeOf(a.AwayClub))
		reflect.Indirect(reflect.ValueOf(&a.AwayClub)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.AwayClub, x.ID) {
			t.Error("foreign key was wrong value", a.AwayClub, x.ID)
		}
	}
}

func testClubMatchupToOneRemoveOpClubUsingAwayClubClub(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a ClubMatchup
	var b Club

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, clubMatchupDBTypes, false, strmangle.SetComplement(clubMatchupPrimaryKeyColumns, clubMatchupColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, clubDBTypes, false, strmangle.SetComplement(clubPrimaryKeyColumns, clubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetAwayClubClub(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveAwayClubClub(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.AwayClubClub().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.AwayClubClub != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.AwayClub) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.AwayClubClubMatchups) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testClubMatchupToOneSetOpClubUsingHomeClubClub(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a ClubMatchup
	var b, c Club

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, clubMatchupDBTypes, false, strmangle.SetComplement(clubMatchupPrimaryKeyColumns, clubMatchupColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, clubDBTypes, false, strmangle.SetComplement(clubPrimaryKeyColumns, clubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, clubDBTypes, false, strmangle.SetComplement(clubPrimaryKeyColumns, clubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Club{&b, &c} {
		err = a.SetHomeClubClub(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.HomeClubClub != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.HomeClubClubMatchups[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.HomeClub, x.ID) {
			t.Error("foreign key was wrong value", a.HomeClub)
		}

		zero := reflect.Zero(reflect.TypeOf(a.HomeClub))
		reflect.Indirect(reflect.ValueOf(&a.HomeClub)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.HomeClub, x.ID) {
			t.Error("foreign key was wrong value", a.HomeClub, x.ID)
		}
	}
}

func testClubMatchupToOneRemoveOpClubUsingHomeClubClub(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a ClubMatchup
	var b Club

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, clubMatchupDBTypes, false, strmangle.SetComplement(clubMatchupPrimaryKeyColumns, clubMatchupColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, clubDBTypes, false, strmangle.SetComplement(clubPrimaryKeyColumns, clubColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetHomeClubClub(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveHomeClubClub(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.HomeClubClub().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.HomeClubClub != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.HomeClub) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.HomeClubClubMatchups) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testClubMatchupToOneSetOpRoundUsingRound(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a ClubMatchup
	var b, c Round

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, clubMatchupDBTypes, false, strmangle.SetComplement(clubMatchupPrimaryKeyColumns, clubMatchupColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, roundDBTypes, false, strmangle.SetComplement(roundPrimaryKeyColumns, roundColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, roundDBTypes, false, strmangle.SetComplement(roundPrimaryKeyColumns, roundColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Round{&b, &c} {
		err = a.SetRound(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Round != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RoundClubMatchups[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.RoundID, x.ID) {
			t.Error("foreign key was wrong value", a.RoundID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.RoundID))
		reflect.Indirect(reflect.ValueOf(&a.RoundID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.RoundID, x.ID) {
			t.Error("foreign key was wrong value", a.RoundID, x.ID)
		}
	}
}

func testClubMatchupToOneRemoveOpRoundUsingRound(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a ClubMatchup
	var b Round

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, clubMatchupDBTypes, false, strmangle.SetComplement(clubMatchupPrimaryKeyColumns, clubMatchupColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, roundDBTypes, false, strmangle.SetComplement(roundPrimaryKeyColumns, roundColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetRound(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveRound(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Round().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Round != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.RoundID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.RoundClubMatchups) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testClubMatchupsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testClubMatchupsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ClubMatchupSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testClubMatchupsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ClubMatchups().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	clubMatchupDBTypes = map[string]string{`ID`: `integer`, `RoundID`: `integer`, `HomeClub`: `integer`, `AwayClub`: `integer`, `GameTime`: `timestamp without time zone`, `HomeClubScore`: `integer`, `AwayClubScore`: `integer`, `Status`: `integer`, `CreatedAt`: `timestamp without time zone`, `DeletedAt`: `timestamp without time zone`}
	_                  = bytes.MinRead
)

func testClubMatchupsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(clubMatchupPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(clubMatchupAllColumns) == len(clubMatchupPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testClubMatchupsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(clubMatchupAllColumns) == len(clubMatchupPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ClubMatchup{}
	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, clubMatchupDBTypes, true, clubMatchupPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(clubMatchupAllColumns, clubMatchupPrimaryKeyColumns) {
		fields = clubMatchupAllColumns
	} else {
		fields = strmangle.SetComplement(
			clubMatchupAllColumns,
			clubMatchupPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ClubMatchupSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testClubMatchupsUpsert(t *testing.T) {
	t.Parallel()

	if len(clubMatchupAllColumns) == len(clubMatchupPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ClubMatchup{}
	if err = randomize.Struct(seed, &o, clubMatchupDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ClubMatchup: %s", err)
	}

	count, err := ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, clubMatchupDBTypes, false, clubMatchupPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ClubMatchup struct: %s", err)
	}

	if err = o.Upsert(tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ClubMatchup: %s", err)
	}

	count, err = ClubMatchups().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
