// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TeamPlayer is an object representing the database table.
type TeamPlayer struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	PlayerID  int       `boil:"player_id" json:"player_id" toml:"player_id" yaml:"player_id"`
	TeamID    int       `boil:"team_id" json:"team_id" toml:"team_id" yaml:"team_id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	DeletedAt time.Time `boil:"deleted_at" json:"deleted_at" toml:"deleted_at" yaml:"deleted_at"`

	R *teamPlayerR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L teamPlayerL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TeamPlayerColumns = struct {
	ID        string
	PlayerID  string
	TeamID    string
	CreatedAt string
	DeletedAt string
}{
	ID:        "id",
	PlayerID:  "player_id",
	TeamID:    "team_id",
	CreatedAt: "created_at",
	DeletedAt: "deleted_at",
}

// Generated where

var TeamPlayerWhere = struct {
	ID        whereHelperint
	PlayerID  whereHelperint
	TeamID    whereHelperint
	CreatedAt whereHelpertime_Time
	DeletedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "`TeamPlayers`.`id`"},
	PlayerID:  whereHelperint{field: "`TeamPlayers`.`player_id`"},
	TeamID:    whereHelperint{field: "`TeamPlayers`.`team_id`"},
	CreatedAt: whereHelpertime_Time{field: "`TeamPlayers`.`created_at`"},
	DeletedAt: whereHelpertime_Time{field: "`TeamPlayers`.`deleted_at`"},
}

// TeamPlayerRels is where relationship names are stored.
var TeamPlayerRels = struct {
	Player                     string
	Team                       string
	TeamPlayerTeamRoundPlayers string
	TeamPlayerTradePlayers     string
}{
	Player:                     "Player",
	Team:                       "Team",
	TeamPlayerTeamRoundPlayers: "TeamPlayerTeamRoundPlayers",
	TeamPlayerTradePlayers:     "TeamPlayerTradePlayers",
}

// teamPlayerR is where relationships are stored.
type teamPlayerR struct {
	Player                     *Player              `boil:"Player" json:"Player" toml:"Player" yaml:"Player"`
	Team                       *Team                `boil:"Team" json:"Team" toml:"Team" yaml:"Team"`
	TeamPlayerTeamRoundPlayers TeamRoundPlayerSlice `boil:"TeamPlayerTeamRoundPlayers" json:"TeamPlayerTeamRoundPlayers" toml:"TeamPlayerTeamRoundPlayers" yaml:"TeamPlayerTeamRoundPlayers"`
	TeamPlayerTradePlayers     TradePlayerSlice     `boil:"TeamPlayerTradePlayers" json:"TeamPlayerTradePlayers" toml:"TeamPlayerTradePlayers" yaml:"TeamPlayerTradePlayers"`
}

// NewStruct creates a new relationship struct
func (*teamPlayerR) NewStruct() *teamPlayerR {
	return &teamPlayerR{}
}

// teamPlayerL is where Load methods for each relationship are stored.
type teamPlayerL struct{}

var (
	teamPlayerAllColumns            = []string{"id", "player_id", "team_id", "created_at", "deleted_at"}
	teamPlayerColumnsWithoutDefault = []string{"player_id", "team_id"}
	teamPlayerColumnsWithDefault    = []string{"id", "created_at", "deleted_at"}
	teamPlayerPrimaryKeyColumns     = []string{"id"}
)

type (
	// TeamPlayerSlice is an alias for a slice of pointers to TeamPlayer.
	// This should generally be used opposed to []TeamPlayer.
	TeamPlayerSlice []*TeamPlayer
	// TeamPlayerHook is the signature for custom TeamPlayer hook methods
	TeamPlayerHook func(boil.Executor, *TeamPlayer) error

	teamPlayerQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	teamPlayerType                 = reflect.TypeOf(&TeamPlayer{})
	teamPlayerMapping              = queries.MakeStructMapping(teamPlayerType)
	teamPlayerPrimaryKeyMapping, _ = queries.BindMapping(teamPlayerType, teamPlayerMapping, teamPlayerPrimaryKeyColumns)
	teamPlayerInsertCacheMut       sync.RWMutex
	teamPlayerInsertCache          = make(map[string]insertCache)
	teamPlayerUpdateCacheMut       sync.RWMutex
	teamPlayerUpdateCache          = make(map[string]updateCache)
	teamPlayerUpsertCacheMut       sync.RWMutex
	teamPlayerUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var teamPlayerBeforeInsertHooks []TeamPlayerHook
var teamPlayerBeforeUpdateHooks []TeamPlayerHook
var teamPlayerBeforeDeleteHooks []TeamPlayerHook
var teamPlayerBeforeUpsertHooks []TeamPlayerHook

var teamPlayerAfterInsertHooks []TeamPlayerHook
var teamPlayerAfterSelectHooks []TeamPlayerHook
var teamPlayerAfterUpdateHooks []TeamPlayerHook
var teamPlayerAfterDeleteHooks []TeamPlayerHook
var teamPlayerAfterUpsertHooks []TeamPlayerHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TeamPlayer) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range teamPlayerBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TeamPlayer) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range teamPlayerBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TeamPlayer) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range teamPlayerBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TeamPlayer) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range teamPlayerBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TeamPlayer) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range teamPlayerAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TeamPlayer) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range teamPlayerAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TeamPlayer) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range teamPlayerAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TeamPlayer) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range teamPlayerAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TeamPlayer) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range teamPlayerAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTeamPlayerHook registers your hook function for all future operations.
func AddTeamPlayerHook(hookPoint boil.HookPoint, teamPlayerHook TeamPlayerHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		teamPlayerBeforeInsertHooks = append(teamPlayerBeforeInsertHooks, teamPlayerHook)
	case boil.BeforeUpdateHook:
		teamPlayerBeforeUpdateHooks = append(teamPlayerBeforeUpdateHooks, teamPlayerHook)
	case boil.BeforeDeleteHook:
		teamPlayerBeforeDeleteHooks = append(teamPlayerBeforeDeleteHooks, teamPlayerHook)
	case boil.BeforeUpsertHook:
		teamPlayerBeforeUpsertHooks = append(teamPlayerBeforeUpsertHooks, teamPlayerHook)
	case boil.AfterInsertHook:
		teamPlayerAfterInsertHooks = append(teamPlayerAfterInsertHooks, teamPlayerHook)
	case boil.AfterSelectHook:
		teamPlayerAfterSelectHooks = append(teamPlayerAfterSelectHooks, teamPlayerHook)
	case boil.AfterUpdateHook:
		teamPlayerAfterUpdateHooks = append(teamPlayerAfterUpdateHooks, teamPlayerHook)
	case boil.AfterDeleteHook:
		teamPlayerAfterDeleteHooks = append(teamPlayerAfterDeleteHooks, teamPlayerHook)
	case boil.AfterUpsertHook:
		teamPlayerAfterUpsertHooks = append(teamPlayerAfterUpsertHooks, teamPlayerHook)
	}
}

// One returns a single teamPlayer record from the query.
func (q teamPlayerQuery) One(exec boil.Executor) (*TeamPlayer, error) {
	o := &TeamPlayer{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for TeamPlayers")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TeamPlayer records from the query.
func (q teamPlayerQuery) All(exec boil.Executor) (TeamPlayerSlice, error) {
	var o []*TeamPlayer

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to TeamPlayer slice")
	}

	if len(teamPlayerAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TeamPlayer records in the query.
func (q teamPlayerQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count TeamPlayers rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q teamPlayerQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if TeamPlayers exists")
	}

	return count > 0, nil
}

// Player pointed to by the foreign key.
func (o *TeamPlayer) Player(mods ...qm.QueryMod) playerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.PlayerID),
	}

	queryMods = append(queryMods, mods...)

	query := Players(queryMods...)
	queries.SetFrom(query.Query, "`Players`")

	return query
}

// Team pointed to by the foreign key.
func (o *TeamPlayer) Team(mods ...qm.QueryMod) teamQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.TeamID),
	}

	queryMods = append(queryMods, mods...)

	query := Teams(queryMods...)
	queries.SetFrom(query.Query, "`Teams`")

	return query
}

// TeamPlayerTeamRoundPlayers retrieves all the TeamRoundPlayer's TeamRoundPlayers with an executor via team_player_id column.
func (o *TeamPlayer) TeamPlayerTeamRoundPlayers(mods ...qm.QueryMod) teamRoundPlayerQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`TeamRoundPlayers`.`team_player_id`=?", o.ID),
	)

	query := TeamRoundPlayers(queryMods...)
	queries.SetFrom(query.Query, "`TeamRoundPlayers`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`TeamRoundPlayers`.*"})
	}

	return query
}

// TeamPlayerTradePlayers retrieves all the TradePlayer's TradePlayers with an executor via team_player_id column.
func (o *TeamPlayer) TeamPlayerTradePlayers(mods ...qm.QueryMod) tradePlayerQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`TradePlayers`.`team_player_id`=?", o.ID),
	)

	query := TradePlayers(queryMods...)
	queries.SetFrom(query.Query, "`TradePlayers`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`TradePlayers`.*"})
	}

	return query
}

// LoadPlayer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (teamPlayerL) LoadPlayer(e boil.Executor, singular bool, maybeTeamPlayer interface{}, mods queries.Applicator) error {
	var slice []*TeamPlayer
	var object *TeamPlayer

	if singular {
		object = maybeTeamPlayer.(*TeamPlayer)
	} else {
		slice = *maybeTeamPlayer.(*[]*TeamPlayer)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &teamPlayerR{}
		}
		args = append(args, object.PlayerID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teamPlayerR{}
			}

			for _, a := range args {
				if a == obj.PlayerID {
					continue Outer
				}
			}

			args = append(args, obj.PlayerID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`Players`),
		qm.WhereIn(`Players.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Player")
	}

	var resultSlice []*Player
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Player")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for Players")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for Players")
	}

	if len(teamPlayerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Player = foreign
		if foreign.R == nil {
			foreign.R = &playerR{}
		}
		foreign.R.PlayerTeamPlayers = append(foreign.R.PlayerTeamPlayers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PlayerID == foreign.ID {
				local.R.Player = foreign
				if foreign.R == nil {
					foreign.R = &playerR{}
				}
				foreign.R.PlayerTeamPlayers = append(foreign.R.PlayerTeamPlayers, local)
				break
			}
		}
	}

	return nil
}

// LoadTeam allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (teamPlayerL) LoadTeam(e boil.Executor, singular bool, maybeTeamPlayer interface{}, mods queries.Applicator) error {
	var slice []*TeamPlayer
	var object *TeamPlayer

	if singular {
		object = maybeTeamPlayer.(*TeamPlayer)
	} else {
		slice = *maybeTeamPlayer.(*[]*TeamPlayer)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &teamPlayerR{}
		}
		args = append(args, object.TeamID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teamPlayerR{}
			}

			for _, a := range args {
				if a == obj.TeamID {
					continue Outer
				}
			}

			args = append(args, obj.TeamID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`Teams`),
		qm.WhereIn(`Teams.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Team")
	}

	var resultSlice []*Team
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Team")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for Teams")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for Teams")
	}

	if len(teamPlayerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Team = foreign
		if foreign.R == nil {
			foreign.R = &teamR{}
		}
		foreign.R.TeamTeamPlayers = append(foreign.R.TeamTeamPlayers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TeamID == foreign.ID {
				local.R.Team = foreign
				if foreign.R == nil {
					foreign.R = &teamR{}
				}
				foreign.R.TeamTeamPlayers = append(foreign.R.TeamTeamPlayers, local)
				break
			}
		}
	}

	return nil
}

// LoadTeamPlayerTeamRoundPlayers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (teamPlayerL) LoadTeamPlayerTeamRoundPlayers(e boil.Executor, singular bool, maybeTeamPlayer interface{}, mods queries.Applicator) error {
	var slice []*TeamPlayer
	var object *TeamPlayer

	if singular {
		object = maybeTeamPlayer.(*TeamPlayer)
	} else {
		slice = *maybeTeamPlayer.(*[]*TeamPlayer)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &teamPlayerR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teamPlayerR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`TeamRoundPlayers`),
		qm.WhereIn(`TeamRoundPlayers.team_player_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TeamRoundPlayers")
	}

	var resultSlice []*TeamRoundPlayer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TeamRoundPlayers")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on TeamRoundPlayers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for TeamRoundPlayers")
	}

	if len(teamRoundPlayerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TeamPlayerTeamRoundPlayers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &teamRoundPlayerR{}
			}
			foreign.R.TeamPlayer = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.TeamPlayerID) {
				local.R.TeamPlayerTeamRoundPlayers = append(local.R.TeamPlayerTeamRoundPlayers, foreign)
				if foreign.R == nil {
					foreign.R = &teamRoundPlayerR{}
				}
				foreign.R.TeamPlayer = local
				break
			}
		}
	}

	return nil
}

// LoadTeamPlayerTradePlayers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (teamPlayerL) LoadTeamPlayerTradePlayers(e boil.Executor, singular bool, maybeTeamPlayer interface{}, mods queries.Applicator) error {
	var slice []*TeamPlayer
	var object *TeamPlayer

	if singular {
		object = maybeTeamPlayer.(*TeamPlayer)
	} else {
		slice = *maybeTeamPlayer.(*[]*TeamPlayer)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &teamPlayerR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teamPlayerR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`TradePlayers`),
		qm.WhereIn(`TradePlayers.team_player_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load TradePlayers")
	}

	var resultSlice []*TradePlayer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice TradePlayers")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on TradePlayers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for TradePlayers")
	}

	if len(tradePlayerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.TeamPlayerTradePlayers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &tradePlayerR{}
			}
			foreign.R.TeamPlayer = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.TeamPlayerID) {
				local.R.TeamPlayerTradePlayers = append(local.R.TeamPlayerTradePlayers, foreign)
				if foreign.R == nil {
					foreign.R = &tradePlayerR{}
				}
				foreign.R.TeamPlayer = local
				break
			}
		}
	}

	return nil
}

// SetPlayer of the teamPlayer to the related item.
// Sets o.R.Player to related.
// Adds o to related.R.PlayerTeamPlayers.
func (o *TeamPlayer) SetPlayer(exec boil.Executor, insert bool, related *Player) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `TeamPlayers` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"player_id"}),
		strmangle.WhereClause("`", "`", 0, teamPlayerPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PlayerID = related.ID
	if o.R == nil {
		o.R = &teamPlayerR{
			Player: related,
		}
	} else {
		o.R.Player = related
	}

	if related.R == nil {
		related.R = &playerR{
			PlayerTeamPlayers: TeamPlayerSlice{o},
		}
	} else {
		related.R.PlayerTeamPlayers = append(related.R.PlayerTeamPlayers, o)
	}

	return nil
}

// SetTeam of the teamPlayer to the related item.
// Sets o.R.Team to related.
// Adds o to related.R.TeamTeamPlayers.
func (o *TeamPlayer) SetTeam(exec boil.Executor, insert bool, related *Team) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `TeamPlayers` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"team_id"}),
		strmangle.WhereClause("`", "`", 0, teamPlayerPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TeamID = related.ID
	if o.R == nil {
		o.R = &teamPlayerR{
			Team: related,
		}
	} else {
		o.R.Team = related
	}

	if related.R == nil {
		related.R = &teamR{
			TeamTeamPlayers: TeamPlayerSlice{o},
		}
	} else {
		related.R.TeamTeamPlayers = append(related.R.TeamTeamPlayers, o)
	}

	return nil
}

// AddTeamPlayerTeamRoundPlayers adds the given related objects to the existing relationships
// of the TeamPlayer, optionally inserting them as new records.
// Appends related to o.R.TeamPlayerTeamRoundPlayers.
// Sets related.R.TeamPlayer appropriately.
func (o *TeamPlayer) AddTeamPlayerTeamRoundPlayers(exec boil.Executor, insert bool, related ...*TeamRoundPlayer) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.TeamPlayerID, o.ID)
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `TeamRoundPlayers` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"team_player_id"}),
				strmangle.WhereClause("`", "`", 0, teamRoundPlayerPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}
			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.TeamPlayerID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &teamPlayerR{
			TeamPlayerTeamRoundPlayers: related,
		}
	} else {
		o.R.TeamPlayerTeamRoundPlayers = append(o.R.TeamPlayerTeamRoundPlayers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &teamRoundPlayerR{
				TeamPlayer: o,
			}
		} else {
			rel.R.TeamPlayer = o
		}
	}
	return nil
}

// SetTeamPlayerTeamRoundPlayers removes all previously related items of the
// TeamPlayer replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TeamPlayer's TeamPlayerTeamRoundPlayers accordingly.
// Replaces o.R.TeamPlayerTeamRoundPlayers with related.
// Sets related.R.TeamPlayer's TeamPlayerTeamRoundPlayers accordingly.
func (o *TeamPlayer) SetTeamPlayerTeamRoundPlayers(exec boil.Executor, insert bool, related ...*TeamRoundPlayer) error {
	query := "update `TeamRoundPlayers` set `team_player_id` = null where `team_player_id` = ?"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.TeamPlayerTeamRoundPlayers {
			queries.SetScanner(&rel.TeamPlayerID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.TeamPlayer = nil
		}

		o.R.TeamPlayerTeamRoundPlayers = nil
	}
	return o.AddTeamPlayerTeamRoundPlayers(exec, insert, related...)
}

// RemoveTeamPlayerTeamRoundPlayers relationships from objects passed in.
// Removes related items from R.TeamPlayerTeamRoundPlayers (uses pointer comparison, removal does not keep order)
// Sets related.R.TeamPlayer.
func (o *TeamPlayer) RemoveTeamPlayerTeamRoundPlayers(exec boil.Executor, related ...*TeamRoundPlayer) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.TeamPlayerID, nil)
		if rel.R != nil {
			rel.R.TeamPlayer = nil
		}
		if _, err = rel.Update(exec, boil.Whitelist("team_player_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.TeamPlayerTeamRoundPlayers {
			if rel != ri {
				continue
			}

			ln := len(o.R.TeamPlayerTeamRoundPlayers)
			if ln > 1 && i < ln-1 {
				o.R.TeamPlayerTeamRoundPlayers[i] = o.R.TeamPlayerTeamRoundPlayers[ln-1]
			}
			o.R.TeamPlayerTeamRoundPlayers = o.R.TeamPlayerTeamRoundPlayers[:ln-1]
			break
		}
	}

	return nil
}

// AddTeamPlayerTradePlayers adds the given related objects to the existing relationships
// of the TeamPlayer, optionally inserting them as new records.
// Appends related to o.R.TeamPlayerTradePlayers.
// Sets related.R.TeamPlayer appropriately.
func (o *TeamPlayer) AddTeamPlayerTradePlayers(exec boil.Executor, insert bool, related ...*TradePlayer) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.TeamPlayerID, o.ID)
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `TradePlayers` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"team_player_id"}),
				strmangle.WhereClause("`", "`", 0, tradePlayerPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}
			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.TeamPlayerID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &teamPlayerR{
			TeamPlayerTradePlayers: related,
		}
	} else {
		o.R.TeamPlayerTradePlayers = append(o.R.TeamPlayerTradePlayers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &tradePlayerR{
				TeamPlayer: o,
			}
		} else {
			rel.R.TeamPlayer = o
		}
	}
	return nil
}

// SetTeamPlayerTradePlayers removes all previously related items of the
// TeamPlayer replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.TeamPlayer's TeamPlayerTradePlayers accordingly.
// Replaces o.R.TeamPlayerTradePlayers with related.
// Sets related.R.TeamPlayer's TeamPlayerTradePlayers accordingly.
func (o *TeamPlayer) SetTeamPlayerTradePlayers(exec boil.Executor, insert bool, related ...*TradePlayer) error {
	query := "update `TradePlayers` set `team_player_id` = null where `team_player_id` = ?"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.TeamPlayerTradePlayers {
			queries.SetScanner(&rel.TeamPlayerID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.TeamPlayer = nil
		}

		o.R.TeamPlayerTradePlayers = nil
	}
	return o.AddTeamPlayerTradePlayers(exec, insert, related...)
}

// RemoveTeamPlayerTradePlayers relationships from objects passed in.
// Removes related items from R.TeamPlayerTradePlayers (uses pointer comparison, removal does not keep order)
// Sets related.R.TeamPlayer.
func (o *TeamPlayer) RemoveTeamPlayerTradePlayers(exec boil.Executor, related ...*TradePlayer) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.TeamPlayerID, nil)
		if rel.R != nil {
			rel.R.TeamPlayer = nil
		}
		if _, err = rel.Update(exec, boil.Whitelist("team_player_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.TeamPlayerTradePlayers {
			if rel != ri {
				continue
			}

			ln := len(o.R.TeamPlayerTradePlayers)
			if ln > 1 && i < ln-1 {
				o.R.TeamPlayerTradePlayers[i] = o.R.TeamPlayerTradePlayers[ln-1]
			}
			o.R.TeamPlayerTradePlayers = o.R.TeamPlayerTradePlayers[:ln-1]
			break
		}
	}

	return nil
}

// TeamPlayers retrieves all the records using an executor.
func TeamPlayers(mods ...qm.QueryMod) teamPlayerQuery {
	mods = append(mods, qm.From("`TeamPlayers`"))
	return teamPlayerQuery{NewQuery(mods...)}
}

// FindTeamPlayer retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTeamPlayer(exec boil.Executor, iD int, selectCols ...string) (*TeamPlayer, error) {
	teamPlayerObj := &TeamPlayer{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `TeamPlayers` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, teamPlayerObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from TeamPlayers")
	}

	return teamPlayerObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TeamPlayer) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no TeamPlayers provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(teamPlayerColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	teamPlayerInsertCacheMut.RLock()
	cache, cached := teamPlayerInsertCache[key]
	teamPlayerInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			teamPlayerAllColumns,
			teamPlayerColumnsWithDefault,
			teamPlayerColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(teamPlayerType, teamPlayerMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(teamPlayerType, teamPlayerMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `TeamPlayers` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `TeamPlayers` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `TeamPlayers` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, teamPlayerPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into TeamPlayers")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == teamPlayerMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}
	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to populate default values for TeamPlayers")
	}

CacheNoHooks:
	if !cached {
		teamPlayerInsertCacheMut.Lock()
		teamPlayerInsertCache[key] = cache
		teamPlayerInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the TeamPlayer.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TeamPlayer) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	teamPlayerUpdateCacheMut.RLock()
	cache, cached := teamPlayerUpdateCache[key]
	teamPlayerUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			teamPlayerAllColumns,
			teamPlayerPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update TeamPlayers, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `TeamPlayers` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, teamPlayerPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(teamPlayerType, teamPlayerMapping, append(wl, teamPlayerPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update TeamPlayers row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for TeamPlayers")
	}

	if !cached {
		teamPlayerUpdateCacheMut.Lock()
		teamPlayerUpdateCache[key] = cache
		teamPlayerUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q teamPlayerQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for TeamPlayers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for TeamPlayers")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TeamPlayerSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teamPlayerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `TeamPlayers` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, teamPlayerPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in teamPlayer slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all teamPlayer")
	}
	return rowsAff, nil
}

var mySQLTeamPlayerUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TeamPlayer) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no TeamPlayers provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(teamPlayerColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTeamPlayerUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	teamPlayerUpsertCacheMut.RLock()
	cache, cached := teamPlayerUpsertCache[key]
	teamPlayerUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			teamPlayerAllColumns,
			teamPlayerColumnsWithDefault,
			teamPlayerColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			teamPlayerAllColumns,
			teamPlayerPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert TeamPlayers, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`TeamPlayers`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `TeamPlayers` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(teamPlayerType, teamPlayerMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(teamPlayerType, teamPlayerMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert for TeamPlayers")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == teamPlayerMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(teamPlayerType, teamPlayerMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to retrieve unique values for TeamPlayers")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}
	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to populate default values for TeamPlayers")
	}

CacheNoHooks:
	if !cached {
		teamPlayerUpsertCacheMut.Lock()
		teamPlayerUpsertCache[key] = cache
		teamPlayerUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single TeamPlayer record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TeamPlayer) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no TeamPlayer provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), teamPlayerPrimaryKeyMapping)
	sql := "DELETE FROM `TeamPlayers` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from TeamPlayers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for TeamPlayers")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q teamPlayerQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no teamPlayerQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from TeamPlayers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for TeamPlayers")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TeamPlayerSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(teamPlayerBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teamPlayerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `TeamPlayers` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, teamPlayerPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from teamPlayer slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for TeamPlayers")
	}

	if len(teamPlayerAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TeamPlayer) Reload(exec boil.Executor) error {
	ret, err := FindTeamPlayer(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TeamPlayerSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TeamPlayerSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teamPlayerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `TeamPlayers`.* FROM `TeamPlayers` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, teamPlayerPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in TeamPlayerSlice")
	}

	*o = slice

	return nil
}

// TeamPlayerExists checks if the TeamPlayer row exists.
func TeamPlayerExists(exec boil.Executor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `TeamPlayers` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if TeamPlayers exists")
	}

	return exists, nil
}
